### ISSUE TITLE
UI improvements 

### ISSUE THREAD

**Issue by latour-gui** [LeGroupeDeFer/IAM#14]
- [x]  bug : when clicking on different cans, the information stacks instead of being replaced
- [x] enhance : different cursor on hover
- [x] enhance : x/96 request received last day ? : explain or change
- [x] bug : wrong date parsing
- [x] bug : edition of geolocation invert long-lat

**Comment by tsepton** [comment]
- [x] Use transition for a smoother user interface

**Comment by findot** [comment]
fixed in 4a86448ca426874206c4014a0339515205c12df2
