### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by sady410** [LeGroupeDeFer/IAM#24]
1) Persona/Context @Khalred 

2) Project global idea (pitch) @Khalred 

3) Méthodologie @Khalred 
    - github 
    - Docker

4) Material/Software (make a scheme):
- Agents: modules/sensors + calibration + encryption (RSA/Ed25519)
    - raspberry @latour-gui 
    - arduino @sady410 
- Openapi @latour-gui 
- Backend: Scala (airframeHttp/slick) + justify choice (why not Play/Finch ?)
    - stack @findot 
        - Database: MariaDB (comme architecture) @findot 
    - architecture (mvc + vite fait les controlleurs) @latour-gui 
    - pq flick & pas play @findot 
- Frontend: SvelteJS/Mapbox + justify choice (why SvelteJS ?) @tsepton 
    - avantage de svelte  @tsepton 
    - dijkstra like @tsepton 

5) Forces @latour-gui 
- security (certification)

6) Improvements: @sady410 
- machine learning 
- sensors' accurcacy
- scaling
- arduino: key configuration must be hardcoded -> solution: rfid
- agents based on wifi

------------
Autre) : Demo video + create user accounts @tsepton , @Khalred

**Comment by sady410** [comment]
https://docs.google.com/presentation/d/11T4hTgHTw_jD7U0y3VWJepJ6nBZqU5A6Yc6kQ2L280E/edit#slide=id.ga5d773e852_0_98

**Comment by latour-gui** [comment]
https://docs.google.com/presentation/d/11T4hTgHTw_jD7U0y3VWJepJ6nBZqU5A6Yc6kQ2L280E/edit?usp=sharing

**Comment by guillaume** [comment]
wrong @guillaume. Bonne chance dans votre projet! :D

**Comment by latour-gui** [comment]
![image](https://user-images.githubusercontent.com/56428897/101397752-63dfe200-38cd-11eb-95dc-45a33b65e32b.png)

**Comment by florian** [comment]
Also wrong @florian.

**Comment by latour-gui** [comment]
yup, sorry I don't know how to prevent notifications retroactively :/
