### ISSUE TITLE
Find an encryption scheme for the Arduino

### ISSUE THREAD

**Issue by findot** [LeGroupeDeFer/IAM#7]
RSA is too heavy to compute for the arduino so we need to find an algorithm that is sufficiently secure but not too computation heavy.

**Comment by Tazoeur** [comment]
change of objectives : now 
- [x] implem verification on server side @findot 
- [x] test that communication between agent & server is wokring properly @sady410

**Comment by Tazoeur** [comment]
- [ ] fix bias on arduino measurement
